/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(calc_phase_diff.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(b2dc0eaa00b3cb430368d932fbec9f39)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/aoa/calc_phase_diff.h>
// pydoc.h is automatically generated in the build directory
#include <calc_phase_diff_pydoc.h>

void bind_calc_phase_diff(py::module& m)
{

    using calc_phase_diff    = ::gr::aoa::calc_phase_diff;


    py::class_<calc_phase_diff, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<calc_phase_diff>>(m, "calc_phase_diff", D(calc_phase_diff))

        .def(py::init(&calc_phase_diff::make),
           py::arg("node_idx"),
           py::arg("norm_spacing"),
           D(calc_phase_diff,make)
        )
        



        ;




}








