/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(rootMUSIC_linear_array.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(61315ff091e5094e82e9d0246f06c584)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/aoa/rootMUSIC_linear_array.h>
// pydoc.h is automatically generated in the build directory
#include <rootMUSIC_linear_array_pydoc.h>

void bind_rootMUSIC_linear_array(py::module& m)
{

    using rootMUSIC_linear_array    = ::gr::aoa::rootMUSIC_linear_array;


    py::class_<rootMUSIC_linear_array, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<rootMUSIC_linear_array>>(m, "rootMUSIC_linear_array", D(rootMUSIC_linear_array))

        .def(py::init(&rootMUSIC_linear_array::make),
           py::arg("norm_spacing"),
           py::arg("num_targets"),
           py::arg("num_ant_ele"),
           D(rootMUSIC_linear_array,make)
        )
        



        ;




}








