/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(shift_phase.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(abf340016bf053679f185474b06b138a)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/aoa/shift_phase.h>
// pydoc.h is automatically generated in the build directory
#include <shift_phase_pydoc.h>

void bind_shift_phase(py::module& m)
{

    using shift_phase    = ::gr::aoa::shift_phase;


    py::class_<shift_phase, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<shift_phase>>(m, "shift_phase", D(shift_phase))

        .def(py::init(&shift_phase::make),
           D(shift_phase,make)
        )
        



        ;




}








