/*
 * Copyright 2011 Free Software Foundation, Inc.
 *
 * This file was generated by gr_modtool, a tool from the GNU Radio framework
 * This file is a part of gr-aoa
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

#ifndef INCLUDED_AOA_API_H
#define INCLUDED_AOA_API_H

#include <gnuradio/attributes.h>

#ifdef gnuradio_aoa_EXPORTS
#define BEAMFORMING_API __GR_ATTR_EXPORT
#else
#define BEAMFORMING_API __GR_ATTR_IMPORT
#endif

#endif /* INCLUDED_AOA_API_H */
